
all:

reset
g++ tc2.cpp -o trabalhocg -lGL -lGLU -lglut tinyxml/tinyxml.cpp tinyxml/tinystr.cpp tinyxml/tinyxmlerror.cpp tinyxml/tinyxmlparser.cpp

./trabalhocg config.xml


clean:
	rm *.o
	rm trabalhocg
	reset
