
##### Makefile

	g++ tc1.cpp -o trabalhocg -lGL -lGLU -lglut tinyxml/tinyxml.cpp tinyxml/tinystr.cpp tinyxml/tinyxmlerror.cpp tinyxml/tinyxmlparser.cpp

	./trabalhocg $1

clean: trabalhocg

	rm trabalhocg






